accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('change_password/', views.change_password, name='change_password'),
    path('<username>/profile/', views.profile, name='profile'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from nturl2path import url2pathname
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

articles/models.py
from distutils.command.upload import upload
from django.db import models
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles') 
    image = models.ImageField(blank=True, upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

from django import forms

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        ),
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        ),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        ),
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = UserChangeForm.Meta.fields

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from .forms import CustomUserCreationForm, CustomUserChangeForm


def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm(request)
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('accounts:login')


def update(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)


def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('accounts:signup')


def change_password(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/password.html', context)


def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    context = {
        'person': person
    }
    return render(request, 'accounts/profile.html', context)


def follow(request, pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    person = get_object_or_404(get_user_model(), pk=pk)
    if person != request.user:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
    return redirect('accounts:profile', person.username)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-outline-success">로그인</button>
</form>
{% endblock content %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn">제출</button>
</form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
{% if user == person %}
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1>{{ person.username }}</h1>
    <a  href="{% url 'accounts:update' %}" class="btn btn-outline-primary">회원 정보 수정</a>
  </div>
  <hr>
  <div class="d-flex justify-content-evenly">
    <div>
      <p class="m-0">게시물</p>
      <p class="text-center m-0">{{ person.article_set.count }}</p>
    </div>
    <div>
      <p class="m-0">팔로워</p>
      <p class="text-center m-0">{{ person.followers.count }}</p>
    </div>
    <div>
      <p class="m-0">팔로우</p>
      <p class="text-center m-0">{{ person.followings.count }}</p>
    </div>
  </div>
  <hr>
{% else %}
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h3>{{ person.username }}</h3>
    {% if request.user in person.followers.all %}
      <a href="{% url 'accounts:follow' person.pk %}"><i class="fa-solid fa-user-minus"></i></a>
      {% else %}
      <a href="{% url 'accounts:follow' person.pk %}"><i class="fa-solid fa-user-plus"></i></a>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-3">
      <p class="m-0">게시물 {{ person.article_set.count }}</p>
    </div>
    <div class="col-3">
      <p class="m-0">팔로워 {{ person.followers.count }}</p>
    </div>
    <div class="col-3">
      <p class="m-0">팔로우 {{ person.followings.count }}</p>
    </div>
  </div>
  <hr>
{% endif %}
<div class="row">
  {% for article in person.article_set.all %}
  <div class="col-4">
    <a href="{% url 'articles:detail' article.pk %}">
      <img src="{{ article.image.url }}" alt="{{ article.image }}" class="card-img-top mb-3">
    </a>
  </div>
  {% endfor %}
</div>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn">제출</button>
</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn">제출</button>
</form>
{% endblock content %}