articles/urls.py
from nturl2path import url2pathname
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from distutils.command.upload import upload
from django.db import models
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles') 
    image = models.ImageField(blank=True, upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ('user', 'like_users', )


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

    class Meta:
        model = Comment
        exclude = ('user', 'article', )

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Article, Comment
from .forms import ArticleForm, CommentForm


def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)


def create(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/create.html', context)


def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


def update(request, pk): 
    article = get_object_or_404(Article, pk=pk)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form
    }
    return render(request, 'articles/update.html', context)


def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')


def comments_create(request, pk):
    article = get_object_or_404(Article, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.article = article
            comment.save()
    return redirect('articles:detail', pk)


def comments_delete(request, article_pk, pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment = get_object_or_404(Comment, pk=pk)

    if article.user == request.user:
        comment.delete()
    return redirect('articles:detail', article_pk)


def likes(request, pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    article = get_object_or_404(Article, pk=pk)

    if article.like_users.filter(pk=request.user.pk).exists():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect('articles:detail', pk)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<h1>create</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button>submit</button>
</form>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>detail</h1>
<div class="row">
  <div class="card">
    <div class="d-flex justify-content-between mt-1">
      <span class="fw-bold">{{ article.user }}</span>
      <div class="btn-group">
        <button class="btn dropdown-toggle btn-sm" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false"></button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuClickableInside">
          <li><a href="{% url 'articles:update' article.pk %}" class="dropdown-item">게시글 수정</a></li>
          <li>
            <form action="{% url 'articles:delete' article.pk %}" method="POST">
              {% csrf_token %}
              <button class="dropdown-item">게시글 삭제</button>
            </form>
          </li>
        </ul>
      </div>
    </div>
    {% if article.image %}
      <img src="{{ article.image.url }}" alt="{{ article.image }}" class="card-img-top mb-3">
    {% endif %}
    {% if request.user in article.like_users.all %}
      <a href="{% url 'articles:likes' article.pk %}">
        <i class="fa-solid fa-heart text-danger fs-3"></i>
      </a>
    {% else %}
      <a href="{% url 'articles:likes' article.pk %}">
        <i class="fa-regular fa-heart text-dark fs-3"></i>
      </a>
    {% endif %}
    <p>좋아요 {{ article.like_users.count }}개</p>
    <div class="card-body p-0">
      <div class="card-text">
        <span class="fw-bold m-0">{{ article.user }}</span>
        <span>{{ article.content }}</span> 
      </div>
    </div>
    <hr>
    <p>댓글 {{ comments.count }}개</p>
    {% for comment in comments %}
    <div class="d-flex justify-content-between mb-1">
      <div>
        <span class="fw-bold m-0">{{ comment.user }}</span>
        <span>{{ comment.content }}</span>
      </div>
      <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-outline-danger btn-sm">delete</button>
      </form>
    </div>
    {% endfor %}
    <p>댓글쓰기</p>
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <button class="btn btn-outline-success btn-sm mb-3">submit</button>
    </form>
    <p class="text-secondary">{{ created_at }}</p>
  </div>
</div>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
  {% for article in articles %}
  <div class="card">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-text">{{ article.content }}</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h1>update</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button>submit</button>
</form>
{% endblock content %}