accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('change_password/', views.change_password, name='change_password'),
    path('<username>/profile/', views.profile, name='profile'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from nturl2path import url2pathname
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid justify-content-around">
      <div>
        <a class="navbar-brand" href="{% url 'articles:index' %}">Main_Logo</a>
      </div>
      <div>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        </form>
      </div>
      <div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'articles:index' %}"><i class="fa-solid fa-house"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articles:create' %}"><i class="fa-regular fa-square-plus"></i></a>
            </li>
            {% if request.user.is_authenticated %}
            <div class="btn-group">
              <button class="btn dropdown-toggle btn-sm" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                <i class="fa-regular fa-user"></i>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuClickableInside">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:delete' %}">회원탈퇴</a>
                </li>
              </ul>
            </div>
            {% else %}
            <div class="btn-group">
              <button class="btn dropdown-toggle btn-sm" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                <i class="fa-regular fa-user"></i>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuClickableInside">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
              </ul>
            </div>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://kit.fontawesome.com/4064b50b6b.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>